# Generated by Django 4.2.4 on 2023-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_boxspacingreview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoxSpacingReview",
        ),
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["review_date"]},
        ),
        migrations.RemoveField(
            model_name="card",
            name="box",
        ),
        migrations.AddField(
            model_name="card",
            name="easiness",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="card",
            name="interval",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="card",
            name="repetitions",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="card",
            name="review_date",
            field=models.DateField(null=True),
        ),
    ]
