# Generated by Django 4.2.4 on 2023-09-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_delete_boxspacingreview_alter_card_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="repetitions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
